services:
  api:
    container_name: "base-api"
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/tef-austral/echo:latest
    ports:
      - 8000:8080
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: base_db
    image: postgres:16
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: