spring:
  application:
    name: tef-austral-api


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI}

# Configuración de Auth0 (usada por el módulo auth)
auth0:
  audience: ${AUTH0_AUDIENCE:https://tef-austral.com/api}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always