auth0:
  audience: ${AUTH0_AUDIENCE:https://tef-austral.com/api}

spring:
  application:
    name: tef-austral-auth-module

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI}
