name: Start Azure VM

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  start-vm:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Start Azure VM
        run: |
          echo "🚀 Starting Azure VM..."
          az vm start \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_VM_NAME }}
          
          echo "⏳ Waiting for VM to be ready..."
          sleep 45
          
          echo "✅ VM is ready!"

      - name: Trigger deployment workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: vm-ready